package com.app.roombooking.db;

import java.sql.*;

public final class DbBootstrap {
    private DbBootstrap() {}

    public static void run() {
        try (Connection c = DbHelper.getConnection()) {
            // THIS METHOD MAKES SCHEME AND SEEDS ONE ATOMIC TRANSACTION.
            c.setAutoCommit(false);
            // ENSURES TABLES/CONSTRAINTS EXIST
            createSchema(c);
            // OPTIONAL: SEEDS A DEFAULT ADMIN AND SAMPLE ROOMS TO USE THE APP ASAP
            seedIfEmpty(c);
            // IF AUTOCOMMIT IS FALSE THIS IS REQUIRED
            c.commit();
            System.out.println("[DbBootstrap] schema ensured & seed applied");
        } catch (Exception e) {
            throw new RuntimeException("DbBootstrap failed", e);
        }
    }
    // THIS METHOD RECEIVES AN OPEN JDBC CONNECTION FROM THE DBHELPER LETTING IT RUN SQL
    private static void createSchema(Connection c) throws SQLException {
        // THIS PART OF THE CODE LETS US RUN THE CODE IN THE SAME OBJECT C SESSION/TRANSACTION
        try (Statement st = c.createStatement()) {
            // THE METHOD executeUpdate CALLS THE JDBC METHOD THAT EXECUTES NON-SELECT SQL STTM
            /* USER IS SKIPPED FOR MVP MODEL FOR NOW
            st.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS users (" +
                            " id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                            " username VARCHAR(50) NOT NULL UNIQUE," +
                            " password_hash VARCHAR(255) NOT NULL," +
                            " role VARCHAR(20) NOT NULL)"
            );*/

            System.out.println("[DbBootstrap] Ensuring table rooms exists");
            st.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS rooms (" +
                    " roomId INTEGER IDENTITY PRIMARY KEY," +
                    " roomName VARCHAR(100) NOT NULL UNIQUE" +
                    ")"
            );

            System.out.println("[DbBootstrap] Ensuring table bookings exists");
            st.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS bookings (" +
                    " id INTEGER IDENTITY PRIMARY KEY," +
                    " roomId INTEGER NOT NULL," +
                    " bookedby VARCHAR(100) NULL," +
                    " startTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    " endTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    " createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL," +
                    " active BOOLEAN DEFAULT TRUE NOT NULL ," +
                    " CONSTRAINT fk_booking_room FOREIGN KEY (roomId) REFERENCES rooms(roomId)," +
                    "CONSTRAINT ck_time_order CHECK (endTime > startTime)" +
                    ")"
            );
        }
    }

    private static void seedIfEmpty(Connection c) throws SQLException {
        // allow disabling in “prod”
        if ("false".equalsIgnoreCase(System.getProperty("SEED_DATA", "true"))) return;

        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM rooms")) {
            rs.next();
            if (rs.getInt(1) == 0) {
                try (PreparedStatement insR = c.prepareStatement(
                        "INSERT INTO rooms(roomName) VALUES (?)")) {
                    insR.setString(1, "Room A");  insR.executeUpdate();
                    insR.setString(1, "Room B");  insR.executeUpdate();
                }
            }
        }
    }
}